version: '3.8'

volumes:
  mariadb_rendu:

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb_rendu_sql
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_rendu:/var/lib/mysql
      - ./docker-config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
  pma:
    image: phpmyadmin:5
    container_name: PhpMyAdmin
    restart: always
    env_file:
      - .env
    environment:
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
    ports:
      - 80:80
