version: '3.8'

volumes:
  mariadb_rendu:

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb_rendu_sql
    restart: always
    environment:
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_ROOT_PASSWORD=dbrootpassword
    volumes:
      - mariadb_rendu:/var/lib/mysql
  pma:
    image: phpmyadmin:5
    container_name: PhpMyAdmin
    restart: always
    environment:
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_ROOT_PASSWORD=dbrootpassword
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
    ports:
      - 80:80
